kube_version: v1.29.4
kube_network_plugin: calico
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_proxy_mode: ipvs
etcd_deployment_type: kubeadm
container_manager: containerd